[workspace]
resolver = "3"
members = ["crates/*", "bridge/*"]

[workspace.dependencies]
cli = { path = "crates/cli", version = "*"}
changepacks-core = { path = "crates/core", version = "*" }
node = { path = "crates/node", version = "*" }
rust = { path = "crates/rust", version = "*" }
python = { path = "crates/python", version = "*" }
dart = { path = "crates/dart", version = "*" }
utils = { path = "crates/utils", version = "*" }
