[package]
name = "cli"
version = "0.1.1"
edition = "2024"

[dependencies]
nanoid = "0.4"
clap = { version = "^4", features = ["derive"] }
utils.workspace = true
changepacks-core.workspace = true
node.workspace = true
rust.workspace = true
python.workspace = true
dart.workspace = true
anyhow = "1.0"
inquire = "0.9"
colored = "3"
serde_json = "1.0"
tokio = { version = "1.48", features = ["fs"] }
futures = "0.3"
