[package]
name = "changepacks-python"
version = "0.1.1"
edition = "2024"

[dependencies]
changepacks-core.workspace = true
changepacks-utils.workspace = true
anyhow = "1.0"
toml = "0.9"
tokio = { version = "1.48", features = ["fs"] }
async-trait = "0.1"
toml_edit = "0.23"
