[package]
name = "changepacks-rust"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"

[dependencies]
toml = "0.9"
changepacks-core.workspace = true
changepacks-utils.workspace = true
anyhow = "1.0"
tokio = { version = "1.48", features = ["fs"] }
async-trait = "0.1"
toml_edit = "0.23"
